# Foundations



  ```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

(last updated: `r format(Sys.time(), "%X, %B %d, %Y")`)

Here I will lay out an axiomatic system that allows the construction of the natural numbers and integers. The following notes are adapted from: <a href="http://dx.doi.org/10.2307/2311096">Margaris 1961</a>
which I thought was a very clear step-by-step construction of the natural numbers and integers. That paper is in a large part based on Edmund Landau's Grundlagen der Analysis (Foundations of Analysis) originally in German (an electronic version of the English translation can be found <a href="https://www.math.purdue.edu/~jlipman/503/foundations-of-analysis.pdf">here</a>).
See also <a href="https://www.math.wustl.edu/~kumar/courses/310-2012/peano.pdf">N. M. Kumar's 2012 Math 310 notes</a> for a nice construction of $\mathbb N$, $\mathbb Z$, and $\mathbb Q$ (but that paper uses the concept of *equivalence classes*).

I have tried to simplify the mathematics found in these works. If you are really interested in the foundations of these number systems, then you should read the linked documents in their entirety. The purpose of this short set of notes is to just give you an idea on what is involved in and sufficient for developing the natural numbers and integers. 

All of this hinges on a background foundation of set theory, in some sense. So if you want to dig further, you should look into resources on the set theory, logic, and the philosophy of mathematics. Bertrand Russel's *Introduction of Mathematical Philosophy* is a good source, or search online for Zermelo-Fraenkel set theory.

Note that there is a huge amount of mathematical literature on the logical and philosophical foundations of arithmetics and mathematics. Mathematicians have devised many different ways to construct the natural numbers and integers (and many other number systems!). Thus, what is presented here is not the only option.


## The natural numbers, $\mathbb N$

First we assume that the concept of quantity exists, that it is a logically coherent idea, and that we can coherently discuss various quantities. We use *numbers* to denote quantities. More specifically, we assume a system of counting. This means that we have the concept of "individual" and that we can understand the concept of a group or collection being composed of many individuals. Two collections of individuals have the same quantity if they can be paired up without leaving anyone alone. That these two collections have the same quantity is what fundamentally identifies a particular number. I propose to think of this as an empirical/physical idea and assume that it is intuitive for you. I do not wish to go in depth into philosophical questions here.

The following axioms establish the foundation for arithmetic and allow building the real number system, calculus, and much of higher mathematics in a very rigorous way. 

We posit the existence of a collection of objects that we will refer to as the *natural numbers*. We also posit the existence of an identity relation "$=$" and an operation "$+1$" on the natural numbers. Typically, these types of constructions use a *successor function* that takes the form $S(n)=n+1$, but I have decided to attempt to leave out such a concept and use "$+1$" directly. When we know we have a number $n$, then we define $n+1$ as to be an operation on $n$. I will assume that this operations results in another number.

First, assume we have a collection of objects, and we are to use names or symbols to refer to each object. Then it is possible to give an object two different names. My son calls me "dada" and you call me "Dr. Stover." It just so happens that "Dr. Stover = dada" in the sense that both vocalizations refer to the same physical human being. So it is like that with numbers. We posit the existence of abstract objects that we call "numbers." We may denote some abstract quantity by $2$ or $1+1$ or $3-1$, but we say $2=1+1=3-1$ because the underlying abstract entity these symbolic representations refer to are in fact the same entity, the number two. 

Now on to the axioms. Now we assume that there is some colleciton of objects, $\mathbb N$, and we refer to this as the set of *natural numbers*.

<div class="thmbox">
**Axioms for $\mathbb N$:**

**Equivalence/identity axioms:**
<ol class="axiom">
<li>
For any $x$, $x=x$.
</li>
<li>
For any $x,y$, if $x=y$ then $y=x$.
</li>
<li>
For any $x,y,z$, if $x=y$ and $y=z$ then $x=z$.
</li>
</ol>

**Axioms for construction of \ $\mathbb N$:**
<ol class="axiom" style="counter-reset: axiom-counter 3;">
<li>
$1\in\mathbb N$
</li>
<li>
For all $n\in\mathbb N$, $n+1\in\mathbb N$.
</li>
<li>
For $n,m\in\mathbb N$, then $n=m$ if and only if $n+1=m+1$.
</li>
<!-- <li> -->
<!-- For $n\in\mathbb N$, if $n=m$, then $m\in\mathbb N$. -->
<!-- </li> -->
<li>
For all $n\in\mathbb N$, $n+1\neq 1$.
</li>
</ol>

<!-- Now we use the symbol "$+$" to denote the successor function: $S(n)=n+1$. So that when we write $n+1$ we are really referring to the natural number that is the successor of $n$. -->

**Induction axiom:**
<ol class="axiom" style="counter-reset: axiom-counter 7;">
<li>
Let $S$ be a subset of $\mathbb N$ and $1\in S$. Also assume that $n\in S$ implies that $n+1\in S$. Then $S=\mathbb N$.
</li>
<!-- <li> -->
<!-- If the statement $p(1)$ is true, and $p(n)$ being true implies that $p(n+1)$ is true, then $p(n)$ is true for all $n\in\mathbb N$. -->
<!-- </li> -->
<!-- <li> -->
<!-- If there is a natural number $n_0\in\mathbb N$ such that statement $p(n_0)$ is true, and $p(n)$ being true implies that $p(n+1)$ is true, then $p(n)$ is true for all $n\geq n_0$. -->
<!-- </li> -->
</ol>
</div>

Note that the way we are using "$+1$" is not really like addition, but as a way to get from one natural number to the next. Furthermore, we introduce the decimal notation that you are familiar with: $1+1=2$, $2+1=3$, $9+1=10$, etc.

Now we define addition and multiplication on natural numbers: 

**Addition:** 
We have that $n+1$ is already identified as a natural number for any natural number $n$. For $n,m\in\mathbb N$ we define addition generally as
$$n+(m+1)=(n+m)+1.$$
That addition is commutative and associative and that $\mathbb N$ is closed under addition follows from this definition and the axioms.

**Multiplication:** 
Define multiplication for any $n\in\mathbb N$ by 
$$n\cdot 1=n$$
and 
$$m\cdot (n+1)=m\cdot n+m$$
for any $n,m\in\mathbb N$. 

This gives us the kind of multiplication that we are used to. It is also possible to show that multiplication is commutative $n\cdot m = m\cdot n$ and associative $(n\cdot m)\cdot k = m\cdot (n\cdot k)$ and that $\mathbb N$ is closed under multiplication. The distributive rule also follows now: $n\cdot(m+k)=n\cdot m+n\cdot k$ for all $n,m,k\in\mathbb N$.

Back to the decimal representation of natural numbers, we have that $35=3\cdot 10+5$, etc.

We define an ordering on $\mathbb N$ such that $n<m$ if there is a $k\in\mathbb N$ such that $n+k=m$. We write $n\leq m$ if either $n<m$ or $n=m$. All of the order properties of natural numbers result, such as transitivity, trichotomy, etc.

## The integers, $\mathbb Z$

Now we posit the existence of a collection of objects $\mathbb Z$ such that $\mathbb N\subset\mathbb Z$. We can also think of the integers as "natural number vectors" $z\in\mathbb Z$, then $z$ points left or right and has a natural number magnitude. 
<!-- Each pair of natural numbers creates an integer in this way: for each $n,m\in\mathbb N$ we create the ordered pair $(n,m)$ and we think of this as being identified with the integer $n-m$ (standing at $n$ and walking to $m$). -->

Now we assume that the set of integers $\mathbb Z$ exists, that $\mathbb N\subset \mathbb Z$, that we can perform an operations "$+1$" and "$-1$" on integers, and that $\mathbb Z$ satisfies the following axioms.

<div class="thmbox">
**Axioms for $\mathbb Z$:**

**Equivalence/identity axioms:**
<ol class="axiom">
<li>
For any $x$, $x=x$.
</li>
<li>
For any $x,y$, if $x=y$ then $y=x$.
</li>
<li>
For any $x,y,z$, if $x=y$ and $y=z$ then $x=z$.
</li>
</ol>

**Axioms for construction of \ $\mathbb Z$:**
<ol class="axiom" style="counter-reset: axiom-counter 3;">
<li>
$1\in\mathbb Z$
</li>
<li>
There is an element $0\in\mathbb Z$ that satisfies $0+1=1$
</li>
<li>
For all $n,m\in\mathbb Z$, $n=m+1 \ \Longleftrightarrow \ n-1=m$.
</li>
<li>
For all $n\in\mathbb Z$, $n-1,n+1\in\mathbb Z$.
</li>
<li>
For $n,m\in\mathbb N$, then $n=m \ \Longleftrightarrow \ n+1=m+1$
<!-- \ \Longleftrightarrow \ n-1=m-1$. -->
</li>
<!-- <li> -->
<!-- For $n\in\mathbb N$, if $n=m$, then $m\in\mathbb N$. -->
<!-- </li> -->
<!-- <li> -->
<!-- For all $n\in\mathbb Z$, $n+1\neq 1$. -->
<!-- </li> -->
</ol>

<!-- Now we use the symbol "$+$" to denote the successor function: $S(n)=n+1$. So that when we write $n+1$ we are really referring to the natural number that is the successor of $n$. -->

**Symmetric induction axiom:**
<ol class="axiom" style="counter-reset: axiom-counter 8;">
<li>
Let $S$ be a subset of $\mathbb Z$ and $1\in S$. Also assume that $n\in S$ implies that $n-1,n+1\in S$. Then $S=\mathbb Z$.
</li>
</ol>
</div>

Now we define addition and multiplication on integers: 

**Addition (and subtraction):** 
We have that $n+1$ and $n-1$ are already identified as a integers for any integer $n$. For $n,m\in\mathbb Z$ we define addition generally as
$$n+(m+1)=(n+m)+1.$$
This also gives us that $n+(m-1)=(n+m)-1$ and that $n+0=n$. That addition is commutative and associative and that $\mathbb Z$ is closed under addition follows from this definition and the axioms as well. We write $n+(-m)$ for 
$$n\underbrace{-1-1-\cdots-1}_{\text{$m$ times}}$$ 
where $n\in\mathbb Z$ is $m\in\mathbb N$. Now we have "negative" numbers defined, i.e. that for any natural number $n$ define $(-n)\overset{def}{=}0-n$ (start with $0$ and apply the "$-1$" operation $n$ times). By this definition of addition and subtraction and the axioms it also follows that $n+(-n)=n-n=0$, that $(-n)$ is the integer such that $n+k+(-n)=k$ for any $k\in\mathbb Z$. Furthermore we get that $-(-n)=n$ for any natural number $n$, and that gives us $-z$ is also well-defined for any integer $z$.

**Multiplication:** 
Define multiplication for any $n\in\mathbb Z$ by 
$$n\cdot 1=n$$
and 
$$m\cdot (n+1)=m\cdot n+m$$
for any $n,m\in\mathbb Z$.

It follows that $m\cdot (n-1)=m\cdot n-m$ and that $0\cdot n=0$ for any $n,m\in\mathbb Z$. From this we can get associativity and commutativity of addition and multiplication and also the distributive property. Note that division is also easily defined by $\frac n m=k$ if $m\cdot k=n$, etc. Of course, this kind of division is not allowed to produce rational numbers yet.

The ordering on $\mathbb Z$ is the same for that of $\mathbb N$: for any $n,m\in \mathbb Z$ we say $n<m$ if there is a natural number $k$ such that $n+k=m$ or equivalently that $n=m-k$.

Now we have the set of integers $\mathbb Z$ with all the properties you are accustomed to. Of course, I have left out many details, and the constructions of $\mathbb N$ and $\mathbb Z$ presented here leave much to be desired. If you would like to see more details and more rigor, see the references cited at the top of the page. 

If you are interested in proving or deriving all the properties of $\mathbb Z$ from these axioms, here is a guide as to the steps to perform. Generally, most steps need an argument using the symmetric induction axiom. These steps also work with deriving all of the properties of $\mathbb N$. See Edmund Landau's Grundlagen der Analysis (Foundations of Analysis) for full proofs for all of $\mathbb N$ (and **many** more details!). There is only one step I found unsatisfactory in Landau's work, and that is that he didn't show that multiplication distributes from the right as well as the left, i.e. that $(x+1)\cdot y =x\cdot y+y$.

<ol>
<li>
We have that $a+(b+1)=(a+b)+1$. Show that $a+(b-1)=(a+b)-1$. This doesn't require induction.
</li>
<li>
Show that $0+a=a+0=a$ for all $a\in\mathbb Z$. Use symmetric induction. Note that $0+0=0+0$ and assume that $0+a=a+0$ for some $a$ and show that it works for $a\pm1$. This shows that addition with zero is commutative and that zero is the additive identity.
</li>
<li>
Show that $a-1=a+(-1)$ for all $a\in\mathbb Z$. Note that $(-1)=0-1$ by definition. 
</li>
<li>
Note that $a+(b+1)=(a+b)+1$ for all $a\in\mathbb Z$, i.e. that $1$ works with the associative rule for any $a,b\in\mathbb Z$. Show that $a+(b+0)=(a+b)+0$ also. Now assume $a+(b+c)=(a+b)+c$ for some $c\in\mathbb Z$, and show that $c\pm1$ also follows the associative rule for arbitrary $a,b$.
<!-- (i.e. show that $a+(b+(c+1))=(a+b)+(c+1)$ and $a+(b+(c-1))=(a+b)+(c-1)$), and use symmetric induction. Now we have that addition is associative. -->
</li>
<li>
Show that $1+a=a+1$ for all $a\in\mathbb Z$. First show that $1+0=0+1$, i.e. that $0$ commutes with $1$. Then assume $1+a=a+1$ for some $a\in\mathbb Z$ and then show $a\pm1$ commutes with $1$, and use symmetric induction. Now we have that all integers commute with zero and one.
</li>
<li>
Now we are ready to prove general commutativity, that $a+b=b+a$ for all $a,b\in\mathbb Z$. Fix $a$ as an arbitrary integer, then we know that $a$ commutes with $0$, and $1$. Assume $b$ commutes with $a$ and show it follows that $b\pm1$ also commutes with $a$, i.e. that $a+(b\pm1)=(b\pm1)+a$. Now again apply symmetric induction. Now we have that addition is commutative.
</li>
<li>
Show that every $a\in\mathbb Z$ commutes with $0$ and $1$ when multiplied, i.e. $0\cdot a=a\cdot 0=0$ and $1\cdot a=a\cdot 1=a$ using symmetric induction.
</li>
<li>
Then prove that $(x+1)\cdot y =x\cdot y+y$ by symmetric induction, i.e. that the definition of multiplication distributes from the left, but we want to show that we can also distribute from the right. This is the trickiest calculation in this list! So now we have that $(x+1)\cdot y =x\cdot y+y$ and also that $x\cdot (y+1) =x\cdot y+x$.
</li>
<li>
Now we can prove that multiplication is commutative by another symmetric induction argument. We know that $0\cdot a=a\cdot 0$ for all $a\in\mathbb Z$, now use symmetric induction.
</li>
<li>
Now prove the distributive rule by symmetric induction. We have that $0\cdot(a+b)=0\cdot a+0\cdot b=0+0=0$ for all $a,b\in\mathbb Z$. Now assume $x\cdot(a+b)=x\cdot a+x\cdot b$ for some $x$ and prove $(x\pm1)\cdot(a+b)=(x\pm1)\cdot a+(x\pm1)\cdot b$, and use symmetric induction.
</li>
<li>
Now prove multiplication is associative, again by symmetric induction.
</li>
</ol>

Finally after the above steps you will have all standard properties of arithmetic including additive and multiplicative identities, that multiplication and addition are commutative and associative, and the distributive property. Note that we also have additive inverses in $\mathbb Z$ by how the addition operation is defined. 

\bigskip
\bigskip
\bigskip


$$
\diamond \S \diamond
$$




## Rational numbers

## Real numbers

# $\large \S$ 1.8 - Some Properties of Real Numbers 
<!--(Kosmala $\S$ 1.8)-->
You should read all of Section 1.8, including the part before Theorem 1.8.4. This includes some results about zeroes of polynomials such as the rational root theorem and a few other results. You should ahve seen most of this material at some point in algebra and calculus courses so we will not cover it. You may be required to use it at times though.


## Some inequality results

<div class="thmbox">
**Theorem 1.8.4**
Suppose that $a,b\in \mathbb R$.
<ol class="paren2-alpha">
<li> If $a<b$, then $a<\frac{a+b}{2}<b$.</li>
<li> If $a,b>0$, then $a<b \ \Longleftrightarrow \ a^2 < b^2 \ \Longleftrightarrow \ \sqrt a <\sqrt b$.</li>
<li> If $a,b \geq 0$, then $\sqrt{ab}\leq \frac{a+b}{2}$. </li>
<li> If $a,b \geq 0$, then $\sqrt{a^2+b^2} \leq a+b$.</li>
</ol>

<a href="javascript:unhide('thm184pf');">Show/hide proof.</a>
<div id="thm184pf" class="hiddendiv">
<!-- <div class="proofbox"> -->
*Proof.*
<ol class="paren2-alpha">
<li> $a<b$ implies that $a+a<a+b<b+b$. Then divide by 2 across.</li>
<li> 
($a<b \Rightarrow a^2<b^2$) 
<div class="inner">
$0<a<b$ implies that $a\cdot a<a\cdot b$ and $b\cdot a<b\cdot b$ thus by transitivity $a^2<b^2$.
</div>
($a^2<b^2 \Rightarrow a<b$)
<div class="inner">
$a^2<b^2$ implies that $0<b^2-a^2=(b-a)(b+a)$. Since $a,b>0$, we know that $a+b>0$. Thus by Section 1.7 \#3(c), $b-a>0$.
</div>
The rest is homework.
</li>
<li>Homework. Hint: square a binomial with square roots in it.</li>
<li>Homework. Hint: square $a+b$.</li>
</ol>
</div>
</div>

## Absolute value results

Recall the definition of the absolute value for real numbers $x\in\mathbb R$:
$$
|x|=
\begin{cases}
x & x\geq 0\\
-x & x<0
\end{cases}
$$
Note that $a\leq|a|$ is always true, and also that $-|a|\leq a\leq |a|$ for all $a\in\mathbb R$. In particular, either $a=|a|$ or $a=-|a|$ is true. We also have that $|a|=\sqrt{|a|^2}$ (Section 1.8, Exercise 14 where some of these are to be proved). 

<div class="thmbox">
**Theorem 1.8.5**
Suppose that $a,b\in \mathbb R$.
<ol class="paren2-alpha">
<li> $|a|\geq0$.</li>
<li> $|a| \leq b$ if and only if $-b\leq a\leq b$.</li>
<li> $|a| \geq b$ if and only if $a\leq-b$ or $a\geq b$.</li>
<li>$|ab|=|a|\cdot|b|$. </li>
<li>$|a+b|\leq|a|+|b|$. (Triangle inequality)</li>
</ol>
<a href="javascript:unhide('thm185pf');">Show/hide proof.</a>
<div id="thm185pf" class="hiddendiv">
<!-- <div class="proofbox"> -->
*Proof.*
<ol class="paren2-alpha">
<li>If $a\geq 0$ then $|a|=a\geq0$. If $a<0$, then $|a|=-a>0$ (see Section 1.7, Exercise 3).</li>
<li>In textbook.</li>
<li>Do yourself. Section 1.8, Exercise 14.</li>
<li>Do yourself. Section 1.8, Exercise 14.</li>
<li>We have that $|a+b|^2=(a+b)^2=a^2+2ab+b^2\leq |a|^2+2|a| |b|+|b|^2 = (|a|+|b|)^2$. We have used the facts that $a^2=|a|^2$ and $ab\leq|ab|=|a||b|$.
<br>
So we have that $|a+b|\leq |a|+|b|$ by Theorem 1.8.4(b) which allows us to take squre roots on both sides of the inequality. 
<br><br>
*Alternative proof:* We have that $-|a|\leq a\leq |a|$. and $-|b|\leq b\leq |b|$. Thus we essentially add these inequalities to get $-|a|-|b|\leq a+b\leq |a|+|b|$. Note that the leftmost side is $-(|a|+|b|)$. Using part (b) of this theorem gives $|a+b|\leq |a|+|b|$. </li>
</ol>
</div>
</div>

The triangle inequality is one of the most useful results that you will use over and over again. Commit it to memory and intuition!

It is also of utmost importance that you get used to translating absolute value equations such as:
<ul>
<li>$|x|\leq a$ to $-a\leq x \leq a$.</li>
<li>$|x|< a$ to $-a< x < a$.</li>
<li>$|x|= a$ to $x=-a$ or $x=a$.</li>
<li>$|x|>a$ to $x<-a$ or $x>a$.</li>
</ul>

These absolute value inequalities are important to remember and will be useful often. 


<div class="thmbox">
**Remark:** (not in text)
<ol class="paren2-alpha">
<li>
For $x,y\in\mathbb R$, $x<y+\epsilon$ for all $\epsilon>0$ if and only if $x\leq y$.
</li>

<li>
For $x,y\in\mathbb R$, $x>y-\epsilon$ for all $\epsilon>0$ if and only if $x\geq y$.
</li>

<li>
For $a\in\mathbb R$, $|a|<\epsilon$ for all $\epsilon>0$ if and only if $a=0$.
</li>
</ol>

<a href="javascript:unhide('absrmkpf');">Show/hide proof.</a>
<div id="absrmkpf" class="hiddendiv">
<!-- <div class="thmbox"> -->
*Proof of (a).*
<ul>
<li style="list-style: '(&#8656;)'; padding-left: 12px;"> <!-- <== is 8656 -->
Assume $x\leq y$. Then for any $\epsilon>0$ we can add $x$ to both sides and get
$0<\epsilon \ \Rightarrow \ x+0<x+\epsilon \leq y+\epsilon$. Thus we have that $x<y+\epsilon$ for any positive $\epsilon$.
</li>
<li style="list-style: '(&#8658;)'; padding-left: 12px;"> <!-- ==> is 8658 -->
Assume that $x<y+\epsilon$ for any positive $\epsilon$. By trichotomy, we know only one of the following is true: $x<y$, $x=y$, or $x>y$. We eliminate the last possbility by contradiction.

Assume that $x>y$. Then we have that $x-y>0$. Now we can let $\epsilon=x-y$. Since this is a positive number, by the first assumption in this proof, we must have that $x<y+\epsilon$ for this particular value of $\epsilon$. But this means that $x<y+\epsilon=y+(x-y)=x$ implying that $x<x$, a contradiction. Therefore we conclude that $x>y$ is not possible. 

Finally $x\leq y$ combines the two remaining options for trichotomy to hold. We are done. You could go ahead and test the other trichotomy options though. 

Assume that $x<y+\epsilon$ for any positive $\epsilon$ and $x=y$. Then $x\leq y$. Done.

Assume that $x<y+\epsilon$ for any positive $\epsilon$ and $x<y$. Then $x\leq y$. Done.
</li>
</ul>

*Proof of (b).*
Use Part (a) and swap $x$ and $y$. This gives $y<x+\epsilon$ if and only if $y\leq x$. But subtracting $\epsilon$ from both sides gives us that $y<x+\epsilon$ is identical to $y-\epsilon<x$. This tells us that $y-\epsilon<x$ for any $\epsilon>0$ if and only if $y\leq x$, which is identical to the statement we want to prove.

<!-- Use Part (a) and replace $x$ and $y$ by $a$ and $b$, respectively. This gives $a<b+\epsilon$ for any $\epsilon>0$ if and only if $a\leq b$. Now replace $b$ by $x$ and $a$ by $y$ to get $y<x+\epsilon$ for any $\epsilon>0$ if and only if $y\leq x$. Then subtract $\epsilon$ from both sides of the initial inequality: $y<x+\epsilon$ is identical to $y-\epsilon<x+\epsilon-\epsilon$. This tells us that $y-\epsilon<x$ for any $\epsilon>0$ if and only if $y\leq x$ which is identical to the statement we want to prove. -->

*Proof of (c).*
Note that $a$ is a fixed real number. 

If $a=0$, then $|a|=0<\epsilon$ for any $\epsilon>0$. I.e. zero is less than every positive real number.

<!-- If $a\neq0$, then $|a|>0$. Now we have found an $\epsilon$ such that $|a| < \epsilon$ is not true. In particular, let $\epsilon_0=|a|>0$. Then for $\epsilon=\epsilon_0>0$ we have that $|a| \nless \epsilon$, a contradiction since we assumed that $|a|<\epsilon$ for all $\epsilon>0$.  -->

If $|a|<\epsilon$ for any $\epsilon>0$, then $-\epsilon<a<\epsilon$ for any $\epsilon>0$. This is identical to $0-\epsilon<a$ and $a<0+\epsilon$ both being true for any $\epsilon>0$. Now apply Parts (a) and (b) with $x=a$ and $y=0$ to get that $0\leq a$ and $a\leq0$ must simultaneously be true. This only occurs when $a=0$. [$\blacksquare$]{style="float:right"}

<!-- By trichotomy, the only possibility is that $a=0$. [$\blacksquare$]{style="float:right"} -->

<!-- *Alternative proof of (c)* If $x\neq0$, then $|x|>0$, and there is a positive real number $b>0$ such that $|x|>b>0$. Let $\epsilon=b$. Then we have proven there exists an $\epsilon>0$ (in particular, $\epsilon=b$) such that $|x| \geq \epsilon$, i.e. that $|x|<\epsilon$ is false. -->

<!-- Since $b>0$ we can find an $\epsilon$ such that $b>\epsilon>0$. So we have proven there exists an $\epsilon>0$ such that $|x| \geq \epsilon$, i.e. that $|x|<\epsilon$ is false. -->

<!-- By trichotomy, the only possibility is that $x=0$. [$\blacksquare$]{style="float:right"} -->
</div>
</div>


<div class="thmbox">
**Corollary 1.8.6**
Suppose that $a,b\in \mathbb R$.
<ol class="paren2-alpha">
<li> $|a-b| \geq |a|-|b|$.</li>
<li> $\Big||a|-|b|\Big| \leq |a-b|$.</li>
</ol>
<!-- </div> -->

<a href="javascript:unhide('cor186pf');">Show/hide proof.</a>
<div id="cor186pf" class="hiddendiv">
<!-- <div class="thmbox"> -->
*Proof of Part (a).*
By the triangle inequality, $|a|=|(a-b)+b|\leq |a-b|+|b|$. Thus $|a-b| \geq |a|-|b|$. [$\blacksquare$]{style="float:right"}

</div>
</div>

The proof of Part (b) is in your homework.


\bigskip
\bigskip
\bigskip

$$
\diamond \S \diamond
$$







