
# Some properties of real numbers 

(last updated: `r format(Sys.time(), "%X, %B %d, %Y")`)

<!--(Kosmala $\S$ 1.8)-->
You should read all of Section 1.8, including the part before Theorem 1.8.4. This includes some results about zeroes of polynomials such as the rational root theorem and a few other results. You should ahve seen most of this material at some point in algebra and calculus courses so we will not cover it. You may be required to use it at times though.


## Some inequality results

<div class="thmbox">
**Theorem 1.8.4**
Suppose that $a,b\in \mathbb R$.
<ol class="paren2-alpha">
<li> If $a<b$, then $a<\frac{a+b}{2}<b$.</li>
<li> If $a,b>0$, then $a<b \ \Longleftrightarrow \ a^2 < b^2 \ \Longleftrightarrow \ \sqrt a <\sqrt b$.</li>
<li> If $a,b \geq 0$, then $\sqrt{ab}\leq \frac{a+b}{2}$. </li>
<li> If $a,b \geq 0$, then $\sqrt{a^2+b^2} \leq a+b$.</li>
</ol>

<a href="javascript:unhide('thm184pf');">Show/hide proof.</a>
<div id="thm184pf" class="hiddendiv">
<!-- <div class="proofbox"> -->
*Proof.*
<ol class="paren2-alpha">
<li> $a<b$ implies that $a+a<a+b<b+b$. Then divide by 2 across.</li>
<li> 
($a<b \Rightarrow a^2<b^2$) 
<div class="inner">
$0<a<b$ implies that $a\cdot a<a\cdot b$ and $b\cdot a<b\cdot b$ thus by transitivity $a^2<b^2$.
</div>
($a^2<b^2 \Rightarrow a<b$)
<div class="inner">
$a^2<b^2$ implies that $0<b^2-a^2=(b-a)(b+a)$. Since $a,b>0$, we know that $a+b>0$. Thus by Section 1.7 \#3(c), $b-a>0$.
</div>
The rest is homework.
</li>
<li>Homework. Hint: square a binomial with square roots in it.</li>
<li>Homework. Hint: square $a+b$.</li>
</ol>
</div>
</div>

## Absolute value results

Recall the definition of the absolute value for real numbers $x\in\mathbb R$:
$$
|x|=
\begin{cases}
x & x\geq 0\\
-x & x<0
\end{cases}
$$
Note that $a\leq|a|$ is always true, and also that $-|a|\leq a\leq |a|$ for all $a\in\mathbb R$. In particular, either $a=|a|$ or $a=-|a|$ is true. We also have that $|a|=\sqrt{|a|^2}$ (Section 1.8, Exercise 14 where some of these are to be proved). 

<div class="thmbox">
**Theorem 1.8.5**
Suppose that $a,b\in \mathbb R$.
<ol class="paren2-alpha">
<li> $|a|\geq0$.</li>
<li> $|a| \leq b$ if and only if $-b\leq a\leq b$.</li>
<li> $|a| \geq b$ if and only if $a\leq-b$ or $a\geq b$.</li>
<li>$|ab|=|a|\cdot|b|$. </li>
<li>$|a+b|\leq|a|+|b|$. (Triangle inequality)</li>
</ol>
<a href="javascript:unhide('thm185pf');">Show/hide proof.</a>
<div id="thm185pf" class="hiddendiv">
<!-- <div class="proofbox"> -->
*Proof.*
<ol class="paren2-alpha">
<li>If $a\geq 0$ then $|a|=a\geq0$. If $a<0$, then $|a|=-a>0$ (see Section 1.7, Exercise 3).</li>
<li>In textbook.</li>
<li>Do yourself. Section 1.8, Exercise 14.</li>
<li>Do yourself. Section 1.8, Exercise 14.</li>
<li>We have that $|a+b|^2=(a+b)^2=a^2+2ab+b^2\leq |a|^2+2|a| |b|+|b|^2 = (|a|+|b|)^2$. We have used the facts that $a^2=|a|^2$ and $ab\leq|ab|=|a||b|$.
<br>
So we have that $|a+b|\leq |a|+|b|$ by Theorem 1.8.4(b) which allows us to take squre roots on both sides of the inequality. 
<br><br>
*Alternative proof:* We have that $-|a|\leq a\leq |a|$. and $-|b|\leq b\leq |b|$. Thus we essentially add these inequalities to get $-|a|-|b|\leq a+b\leq |a|+|b|$. Note that the leftmost side is $-(|a|+|b|)$. Using part (b) of this theorem gives $|a+b|\leq |a|+|b|$. </li>
</ol>
</div>
</div>

The triangle inequality is one of the most useful results that you will use over and over again. Commit it to memory and intuition!

It is also of utmost importance that you get used to translating absolute value equations such as:
<ul>
<li>$|x|\leq a$ to $-a\leq x \leq a$.</li>
<li>$|x|< a$ to $-a< x < a$.</li>
<li>$|x|= a$ to $x=-a$ or $x=a$.</li>
<li>$|x|>a$ to $x<-a$ or $x>a$.</li>
</ul>

These absolute value inequalities are important to remember and will be useful often. 


<div class="thmbox">
**Remark:** (not in text)
<ol class="paren2-alpha">
<li>
For $x,y\in\mathbb R$, $x<y+\epsilon$ for all $\epsilon>0$ if and only if $x\leq y$.
</li>

<li>
For $x,y\in\mathbb R$, $x>y-\epsilon$ for all $\epsilon>0$ if and only if $x\geq y$.
</li>

<li>
For $a\in\mathbb R$, $|a|<\epsilon$ for all $\epsilon>0$ if and only if $a=0$.
</li>
</ol>

<a href="javascript:unhide('absrmkpf');">Show/hide proof.</a>
<div id="absrmkpf" class="hiddendiv">
<!-- <div class="thmbox"> -->
*Proof of (a).*
<ul>
<li style="list-style: '(&#8656;)'; padding-left: 12px;"> <!-- <== is 8656 -->
Assume $x\leq y$. Then for any $\epsilon>0$ we can add $x$ to both sides and get
$0<\epsilon \ \Rightarrow \ x+0<x+\epsilon \leq y+\epsilon$. Thus we have that $x<y+\epsilon$ for any positive $\epsilon$.
</li>
<li style="list-style: '(&#8658;)'; padding-left: 12px;"> <!-- ==> is 8658 -->
Assume that $x<y+\epsilon$ for any positive $\epsilon$. By trichotomy, we know only one of the following is true: $x<y$, $x=y$, or $x>y$. We eliminate the last possbility by contradiction.

Assume that $x>y$. Then we have that $x-y>0$. Now we can let $\epsilon=x-y$. Since this is a positive number, by the first assumption in this proof, we must have that $x<y+\epsilon$ for this particular value of $\epsilon$. But this means that $x<y+\epsilon=y+(x-y)=x$ implying that $x<x$, a contradiction. Therefore we conclude that $x>y$ is not possible. 

Finally $x\leq y$ combines the two remaining options for trichotomy to hold. We are done. You could go ahead and test the other trichotomy options though. 

Assume that $x<y+\epsilon$ for any positive $\epsilon$ and $x=y$. Then $x\leq y$. Done.

Assume that $x<y+\epsilon$ for any positive $\epsilon$ and $x<y$. Then $x\leq y$. Done.
</li>
</ul>

*Proof of (b).*
Use Part (a) and swap $x$ and $y$. This gives $y<x+\epsilon$ if and only if $y\leq x$. But subtracting $\epsilon$ from both sides gives us that $y<x+\epsilon$ is identical to $y-\epsilon<x$. This tells us that $y-\epsilon<x$ for any $\epsilon>0$ if and only if $y\leq x$, which is identical to the statement we want to prove.

<!-- Use Part (a) and replace $x$ and $y$ by $a$ and $b$, respectively. This gives $a<b+\epsilon$ for any $\epsilon>0$ if and only if $a\leq b$. Now replace $b$ by $x$ and $a$ by $y$ to get $y<x+\epsilon$ for any $\epsilon>0$ if and only if $y\leq x$. Then subtract $\epsilon$ from both sides of the initial inequality: $y<x+\epsilon$ is identical to $y-\epsilon<x+\epsilon-\epsilon$. This tells us that $y-\epsilon<x$ for any $\epsilon>0$ if and only if $y\leq x$ which is identical to the statement we want to prove. -->

*Proof of (c).*
Note that $a$ is a fixed real number. 

If $a=0$, then $|a|=0<\epsilon$ for any $\epsilon>0$. I.e. zero is less than every positive real number.

<!-- If $a\neq0$, then $|a|>0$. Now we have found an $\epsilon$ such that $|a| < \epsilon$ is not true. In particular, let $\epsilon_0=|a|>0$. Then for $\epsilon=\epsilon_0>0$ we have that $|a| \nless \epsilon$, a contradiction since we assumed that $|a|<\epsilon$ for all $\epsilon>0$.  -->

If $|a|<\epsilon$ for any $\epsilon>0$, then $-\epsilon<a<\epsilon$ for any $\epsilon>0$. This is identical to $0-\epsilon<a$ and $a<0+\epsilon$ both being true for any $\epsilon>0$. Now apply Parts (a) and (b) with $x=a$ and $y=0$ to get that $0\leq a$ and $a\leq0$ must simultaneously be true. This only occurs when $a=0$. [$\blacksquare$]{style="float:right"}

<!-- By trichotomy, the only possibility is that $a=0$. [$\blacksquare$]{style="float:right"} -->

<!-- *Alternative proof of (c)* If $x\neq0$, then $|x|>0$, and there is a positive real number $b>0$ such that $|x|>b>0$. Let $\epsilon=b$. Then we have proven there exists an $\epsilon>0$ (in particular, $\epsilon=b$) such that $|x| \geq \epsilon$, i.e. that $|x|<\epsilon$ is false. -->

<!-- Since $b>0$ we can find an $\epsilon$ such that $b>\epsilon>0$. So we have proven there exists an $\epsilon>0$ such that $|x| \geq \epsilon$, i.e. that $|x|<\epsilon$ is false. -->

<!-- By trichotomy, the only possibility is that $x=0$. [$\blacksquare$]{style="float:right"} -->
</div>
</div>


<div class="thmbox">
**Corollary 1.8.6**
Suppose that $a,b\in \mathbb R$.
<ol class="paren2-alpha">
<li> $|a-b| \geq |a|-|b|$.</li>
<li> $\Big||a|-|b|\Big| \leq |a-b|$.</li>
</ol>
<!-- </div> -->

<a href="javascript:unhide('cor186pf');">Show/hide proof.</a>
<div id="cor186pf" class="hiddendiv">
<!-- <div class="thmbox"> -->
*Proof of Part (a).*
By the triangle inequality, $|a|=|(a-b)+b|\leq |a-b|+|b|$. Thus $|a-b| \geq |a|-|b|$. [$\blacksquare$]{style="float:right"}

</div>
</div>

The proof of Part (b) is in your homework.


\bigskip
\bigskip
\bigskip

$$
\diamond \S \diamond
$$







